#!/usr/bin/env node
// Rebuild application code from verified packs without deleting local originals.
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {ROOT, auditSecrets, auditEligibility} from './package-production.mjs';
import {verifyPacks} from './pack-media.mjs';

const media = await verifyPacks();
await auditEligibility(media.files);
if ((await auditSecrets(ROOT, media.contents)).uploadFindings.length) throw Error('Upload secret audit failed');
execFileSync(process.execPath, [path.join(ROOT, 'app/node_modules/vite/bin/vite.js'), 'build', '--mode', 'pages'], {
  cwd: path.join(ROOT, 'app'), stdio: 'inherit',
});
const dist = path.join(ROOT, 'app/dist');
const output = [];
async function walk(dir, prefix = '') {
  for (const entry of await fs.readdir(dir, {withFileTypes: true})) {
    if (entry.isSymbolicLink()) throw Error('Build symlink rejected');
    const relative = prefix + entry.name;
    if (entry.isDirectory()) await walk(path.join(dir, entry.name), relative + '/');
    else output.push(relative);
  }
}
await walk(dist);
const fixed = new Set(['index.html', 'experiment.html', '.nojekyll', 'PLAYCANVAS-LICENSE.txt', 'FFLATE-LICENSE.txt', 'ASSET-NOTICES.md', 'level-cache-sw.js','level-cache-core.js']);
for (const name of output) {
  if (!fixed.has(name) && !/^assets\/[A-Za-z0-9_-]+\.(js|css)$/.test(name)) throw Error(`Unexpected build output: ${name}`);
}
for (const required of fixed) if (!output.includes(required)) throw Error(`Missing build output: ${required}`);
for (const name of output) {
  const target = path.join(ROOT, 'docs', name);
  // Only fixed generated app outputs are replaced. Production media is untouched.
  await fs.mkdir(path.dirname(target), {recursive: true});
  for (const candidate of [path.join(ROOT, 'docs'), path.dirname(target), target]) {
    try { if ((await fs.lstat(candidate)).isSymbolicLink()) throw Error('Publish symlink rejected'); }
    catch (e) { if (e.code !== 'ENOENT') throw e; }
  }
  await fs.copyFile(path.join(dist, name), target);
}
// Old hashed bundles stay on disk; only the current bundle is Git-eligible.
const bundles = output.filter(name => name.startsWith('assets/')).sort();
const ignorePath = path.join(ROOT, 'docs/.gitignore');
try { if ((await fs.lstat(ignorePath)).isSymbolicLink()) throw Error('Ignore symlink rejected'); }
catch (e) { if (e.code !== 'ENOENT') throw e; }
await fs.writeFile(ignorePath, '# Generated by scripts/build-pages.mjs; retain only current bundles in Git.\n/assets/*\n' + bundles.map(name => '!/' + name).join('\n') + '\n');
await verifyPacks();
if ((await auditSecrets(ROOT, media.contents)).uploadFindings.length) throw Error('Built output secret audit failed');
console.log(`Prepared ${output.length} app files and ${media.manifest.packs.length} media ZIPs in docs/. Loose media and old bundles remain on disk, ignored.`);
